remote_theme: sighingnow/jekyll-gitbook

title: GearList
longtitle: GearList
author: Cookie Blue
github_username: cookie-blue

ordered_collections:
  - pages
  - other

collections:
  pages:
    output: true
    permalink: /:title
    order:
      - workwear.md
      - firefighting.md
      - puppy.md
      - tactical.md
  other:
    output: true
    permalink: /:title

toc:
  enabled: true
  h_min: 1
  h_max: 3

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
